chrome.runtime.onInstalled.addListener(() => {
  const bookmarksToAdd = [
    
    { title: "💡HEWP", url: "https://works.haryana.gov.in/HEWP_Login/login.aspx" },
    { title: "👤Login", url: "javascript:(function(){const wait=ms=>new Promise(r=>setTimeout(r,ms));(async function(){document.getElementById('alogin')?.click();await wait(500);document.getElementById('contractorbtn')?.click();await wait(300);const captcha=document.getElementById('txtCaptcha');if(captcha){captcha.scrollIntoView({behavior:'smooth',block:'center'});captcha.focus();captcha.style.border='2px solid red';setTimeout(()=>captcha.style.border='',1500);}})();})();" },
    
    { title: "➕AddBill", url: "javascript:(function(){const wait=ms=>new Promise(r=>setTimeout(r,ms));(async function(){document.getElementById('sidebarCollapse')?.click();await wait(300);document.querySelector('a.nav-link[href=\"#actmenucon\"]')?.click();await wait(300);const navLink=Array.from(document.querySelectorAll('a.nav-link')).find(a=>a.getAttribute('href')?.includes('Est_Add_Items_emb.aspx')&&a.textContent.trim().includes('Submit Bill to JE'));navLink?.click();})();})();" },
    { title: "🔍Tender", url: "javascript:(function(){const%20existingInput=document.querySelector('%23independentTenderSearch%20input');if(existingInput){existingInput.scrollIntoView({behavior:'smooth',block:'center'});existingInput.focus();return;}const%20select=document.getElementById('ddltender');if(!select)return;select.scrollIntoView({behavior:'smooth',block:'center'});select.style.border='3px%20solid%20red';setTimeout(()=%3Eselect.style.border='',2000);const%20wrapper=document.createElement('div');wrapper.id='independentTenderSearch';Object.assign(wrapper.style,{position:'relative',marginBottom:'10px'});const%20input=document.createElement('input');input.type='text';input.placeholder='%F0%9F%94%8D%20Search%20tenders...';Object.assign(input.style,{width:'100%',padding:'6px',boxSizing:'border-box'});const%20list=document.createElement('div');Object.assign(list.style,{border:'1px%20solid%20%23ccc',maxHeight:'200px',overflowY:'auto',marginTop:'2px',background:'%23fff',position:'absolute',width:'100%',zIndex:'9999'});wrapper.appendChild(input);wrapper.appendChild(list);select.parentNode.insertBefore(wrapper,select);const%20allOptions=[...select.options].filter(opt=%3Eopt.value!=='Select%20One');function%20escapeRegex(text){return%20text.replace(/[.*+?^${}()|[%5C%5D%5C%5C]/g,'%5C%24%26');}function%20render(matches){list.innerHTML='';const%20searchText=input.value.trim().toLowerCase();matches.forEach(opt=%3E{const%20item=document.createElement('div');Object.assign(item.style,{padding:'5px%208px',cursor:'pointer',backgroundColor:'%23fff9c4',color:'%23000'});if(searchText.length%3E0){const%20regex=new%20RegExp(%60(${escapeRegex(searchText)})%60,'gi');item.innerHTML=opt.text.replace(regex,'%3Cspan%20style=%22color:%20red;%20font-weight:%20bold;%22%3E%241%3C/span%3E');}else{item.textContent=opt.text;}item.addEventListener('mouseover',()=%3E{item.style.backgroundColor='%231565c0';item.style.color='%23fff';});item.addEventListener('mouseout',()=%3E{item.style.backgroundColor='%23fff9c4';item.style.color='%23000';});item.addEventListener('mousedown',()=%3E{select.value=opt.value;const%20event=new%20Event('change',{bubbles:true,cancelable:true});select.dispatchEvent(event);if(typeof%20select.onchange==='function')%20select.onchange();else%20if(typeof%20__doPostBack==='function')%20__doPostBack('_ctl0%24maincontentcm%24ddltender','');list.innerHTML='';input.value='';});list.appendChild(item);});}input.addEventListener('input',()=%3E{const%20val=input.value.toLowerCase();const%20matches=allOptions.filter(opt=%3Eopt.text.toLowerCase().includes(val));render(matches);});input.addEventListener('focus',()=%3Erender(allOptions));input.addEventListener('blur',()=%3EsetTimeout(()=%3E{list.innerHTML='';},200));input.focus();input.scrollIntoView({behavior:'smooth',block:'center'});})();" },
    { title: "🎯Item", url: "javascript:(function(){const%20e=document.querySelector(%22%23independentItemSearch%20input%22);if(e)return%20e.focus(),void%20e.scrollIntoView({behavior:%22smooth%22,block:%22center%22});const%20t=document.querySelector(%22%23ddlitemnumber%22);if(!t)return;t.scrollIntoView({behavior:%22smooth%22,block:%22center%22}),t.style.border=%223px%20solid%20red%22,setTimeout(()=%3Et.style.border=%22%22,2e3);const%20n=document.createElement(%22div%22);n.id=%22independentItemSearch%22,n.style.position=%22relative%22,n.style.marginBottom=%2210px%22;const%20o=document.createElement(%22input%22);o.type=%22text%22,o.placeholder=%22%F0%9F%94%8D%20Search%20items...%22,o.style.width=%22100%25%22,o.style.padding=%226px%22,o.style.boxSizing=%22border-box%22;const%20l=document.createElement(%22div%22);l.style.border=%221px%20solid%20%23ccc%22,l.style.maxHeight=%22200px%22,l.style.overflowY=%22auto%22,l.style.marginTop=%222px%22,l.style.background=%22%23fff%22,l.style.position=%22absolute%22,l.style.width=%22100%25%22,l.style.zIndex=%229999%22,n.appendChild(o),n.appendChild(l),t.parentNode.insertBefore(n,t);const%20i=[...t.options].filter(e=%3E%22Select%20One%22!==e.value);function%20r(e){l.innerHTML=%22%22,e.forEach(e=%3E{const%20n=document.createElement(%22div%22);n.style.padding=%225px%208px%22,n.style.cursor=%22pointer%22,n.style.background=%22%23fff9c4%22,n.style.color=%22%23000%22;const%20i=o.value.trim().toLowerCase();if(i.length%3E0){const%20r=i.replace(/[.*+?^${}()|[%5C%5D%5C%5C]/g,%22%5C%5C%24%26%22),c=new%20RegExp(%60(${r})%60,%22gi%22);n.innerHTML=e.text.replace(c,%27%3Cspan%20style=%22color:%20red;%20font-weight:%20bold;%22%3E%241%3C/span%3E%27)}else%20n.textContent=e.text;n.onmouseover=()=%3E{n.style.background=%22%231565c0%22,n.style.color=%22%23fff%22},n.onmouseout=()=%3E{n.style.background=%22%23fff9c4%22,n.style.color=%22%23000%22},n.onmousedown=function(){t.value=e.value,t.dispatchEvent(new%20Event(%22change%22)),l.innerHTML=%22%22,o.value=%22%22},l.appendChild(n)})}o.addEventListener(%22input%22,function(){const%20e=this.value.toLowerCase(),n=i.filter(t=%3Et.text.toLowerCase().includes(e));r(n)}),o.addEventListener(%22focus%22,()=%3Er(i)),o.addEventListener(%22blur%22,()=%3EsetTimeout(()=%3El.innerHTML=%22%22,200)),setTimeout(()=%3E{o.focus(),o.scrollIntoView({behavior:%22smooth%22,block:%22center%22})},500);})();" }, 

    { title: "🆕Entries", url: "javascript:(function(){ const r = document.getElementById('rblitemshsr_1'); if (r) { r.click(); r.scrollIntoView({behavior: 'smooth', block: 'start'}); }})();" },

    { title: "📁ChooseExcel", url: "javascript:(function(){const wait=ms=>new Promise(r=>setTimeout(r,ms));(async function(){document.querySelector('button[data-bs-target=\"#MyPopup\"]')?.click();await wait(200);document.getElementById('FileUploadexcel')?.click();})();})();" },
    { title: "🔼Upload", url: "javascript:(function(){document.getElementById(\"btn_excel\")?.click();})();" },
    { title: "✅CopyExcel Data", url: "javascript:(function(){ document.getElementById('btncopyexcel')?.click();})();" },
    { title: "✅DONE", url: "javascript:(function(){ const wait = ms => new Promise(r => setTimeout(r, ms)); (async function(){ const okBtn = document.querySelector('button.confirm'); if (okBtn && okBtn.textContent.trim().toLowerCase() === 'ok') okBtn.click(); await wait(500); document.querySelector('button[data-bs-dismiss=\"modal\"]')?.click(); await wait(500); const r = document.getElementById('rblitemshsr_1'); if (r) { r.click(); r.scrollIntoView({behavior: 'smooth', block: 'start'}); } })();})();" },
    { title: "📤Anex", url: "javascript:(function(){var fileInput=document.getElementById('FileUpload3');if(fileInput){fileInput.click();}else{alert('File input not found.');}})();" },
    { title: "🚀Manual add", url: "javascript:(function(){var btn=document.getElementById('btn_add_Description');if(btn){btn.click();}else{alert('Button not found.');}})();" },
    { title: "⚖️MaxQTY", url: "javascript:(()=>{const v=document.getElementById('lbltobeexecuted'),u=document.getElementById('lbltobeexecutedunit');if(!v||!u)return alert('Contact @mrgargsir.');const dn=parseFloat(v.textContent);if(isNaN(dn))return alert('Value is not a number.');const unit=u.textContent.trim(),al=(dn*0.25).toFixed(2),total=(dn*1.25).toFixed(2),msg=`⚖️ DNIT QTY       = ${dn} ${unit}\n➕ ALLOWANCE 25%  = ${al} ${unit}\n✅ TOTAL          = ${total} ${unit}`;try{alert(msg)}catch{if(Notification.permission==='granted')new Notification(msg);else if(Notification.permission!=='denied')Notification.requestPermission().then(p=>p==='granted'?new Notification(msg):alert(msg));else alert(msg)}})();" },
    { title: "MRGARGSIR", url: "https://github.com/mrgargsir" },
    
  ];

  
 
 chrome.bookmarks.getChildren("1", (existingBookmarks) => {
    const titlesToRemove = bookmarksToAdd.map(b => b.title);

    // Remove existing bookmarks with same titles
    existingBookmarks.forEach(b => {
      if (titlesToRemove.includes(b.title)) {
        chrome.bookmarks.remove(b.id);
      }
    });

    // Add new bookmarks
    bookmarksToAdd.forEach(bookmark => {
      chrome.bookmarks.create({
        parentId: "1",
        title: bookmark.title,
        url: bookmark.url
      });
    });
  });
});
