name: Chrome Extension Packager

on:
  push:
    branches: [ main ]
    paths: [ 'src/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Install Chrome
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # 3. Create ZIP
      - name: Package ZIP
        run: |
          cd src
          zip -r ../extension_${{ github.sha }}.zip *
          
      # 4. Create CRX
      - name: Package CRX
        env:
          PRIVATE_KEY: ${{ secrets.EXTENSION_KEY }}
        run: |
          echo "$PRIVATE_KEY" > key.pem
          google-chrome --pack-extension=src --pack-extension-key=key.pem --no-sandbox
          mv src.crx extension_${{ github.sha }}.crx
          rm key.pem

- name: Debug File Existence
  run: |
    ls -la
    ls -la extension_${{ github.sha }}.*

    
      # 5. Upload Artifacts (with proper retention)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: extension-build
          path: |
            extension_${{ github.sha }}.zip
            extension_${{ github.sha }}.crx
          retention-days: 7  # Automatically deletes after 1 week

      # 6. Create Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.sha }}
          name: "Extension v${{ github.sha }}"
          body: "Automatically built extension packages"
          files: |
            extension_${{ github.sha }}.zip
            extension_${{ github.sha }}.crx
