name: Build Extension

on:
  push:
    branches: [ main ]
    paths: [ 'src/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Chrome
      run: sudo apt-get install -y google-chrome-stable

    - name: Make ZIP
      run: |
        cd src
        zip -r ../extension.zip *
        mv ../extension.zip extension-v${{ github.run_number }}.zip

    - name: Make CRX
      env:
        PRIVATE_KEY: ${{ secrets.EXTENSION_KEY }}
      run: |
        echo "$PRIVATE_KEY" > key.pem
        google-chrome --pack-extension=src --pack-extension-key=key.pem --no-sandbox
        mv src.crx extension-v${{ github.run_number }}.crx
        rm key.pem

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          extension-v${{ github.run_number }}.zip
          extension-v${{ github.run_number }}.crx
